version: '3'

networks:
  backend_network: #Réseau prive API <-> BDD (inaccessible depuis l'extérieur)
    internal: true
  frontend_network:
    driver: bridge  

services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bibliotech_db
    volumes:
      - db_data:/var/lib/mysql
      - ./db-init/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      interval: 5s

  api:
    build: ./server
    expose:
      - "3000" #API EXPOSE UNIQUEMENT SUR LE RESEAU PRIVE
    depends_on:
      - db
    networks:
      - backend_network
      - frontend_network

  frontend:
    build: ./client
    ports:
      - "8080:80" #seul le frontend est accessible facilement
    depends_on:
      - api
    networks:
      - frontend_network

volumes:
  db_data: